apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "your-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "your-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "your-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "your-app.name" . }}
    spec:
      containers:
        - name: {{ include "your-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
