name: Infracost Cost Estimation
 
on:
  push:
    paths:
      - 'vpc/**'
      - 'eks/**'
      - '.github/workflows/infracost.yml'
    branches: [main]
  workflow_dispatch:
 
jobs:
  infracost:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
 
    - name: Setup Infracost
      uses: infracost/actions/setup@v2
 
    - name: Generate Infracost cost estimate
      run: |
        infracost breakdown --path=eks/ --format=json --out-file=/tmp/infracost.json
        infracost output --path=/tmp/infracost.json --format=table
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
